//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ukraine
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int o_ID { get; set; }
        public int o_clientID { get; set; }
        public int o_adType { get; set; }
        public int o_managerID { get; set; }
        public int o_durationInSecond { get; set; }
        public decimal o_cost { get; set; }
        public System.DateTime o_date { get; set; }
    
        public virtual AdvertType AdvertType { get; set; }
        public virtual Client Client { get; set; }
        public virtual User User { get; set; }
    }
}
